# generated by mBlock5 for codey & rocky
# codes make you happy
import codey, event, time, uos
import urequests as requests

class Setting():
    def __init__(self):
        codey.speaker.volume = 10
    
    def connectWifi(self):
        codey.wifi.start('Rakuten-6F13', '6U622R2F84', codey.wifi.STA)
        time.sleep(3)
        if codey.wifi.is_connected():
            codey.emotion.smile()
        else:
            codey.emotion.shiver()

class Moving(Setting):
    @event.button_a_pressed
    def on_button_a_pressed():
        codey.speaker.play_melody('hello.wav')
        codey.display.show_image("00003c7e7e3c000000003c7e7e3c0000") 
        codey.display.show('12/26 5:55', wait = True)

    @event.button_b_pressed
    def on_button_b_pressed1():
        codey.speaker.play_melody('yeah.wav')
        codey.display.show_image("000c18181c0c000000000c1c18180c00")
        nowtime = time.time()
        codey.display.show(nowtime, wait = False)
        
    @event.button_c_pressed
    def on_button_c_pressed2():
        codey.speaker.play_melody('sad.wav')
        codey.display.show_image("00000c1e3e3c000000003c3e1e0c0000")
        codey.display.show(uos.uname().sysname)
        
        

s = Setting()          
s.connectWifi()
Moving()
